// ===================================================
// This TB is generated by ChatGPT to test APB slave
//====================================================
`timescale 1ns / 100ps
`include "../APB_uart.sv"


module tb_apb_slave;

// Parameters
parameter DW = 32;  // Data width
parameter AW = 32;  // Address width
localparam CW = 1 + DW + AW;  // Command width
localparam RW = DW;  // Response width

// Signals
logic CLK;
logic RESETn;
logic [CW-1:0] i_cmd;
logic i_valid;
logic [RW-1:0] o_resp;
logic o_ready;
logic [AW-1:0] pADDR;
logic pSELx;
logic pENABLE;
logic pWRITE;
logic [DW-1:0] pWDATA;
logic [DW-1:0] pRDATA;
logic pREADY;
logic [15:0] switch;
logic [15:0] led;
logic pSLVERR;
logic tx;

// Device Under Test
APB_uart #(
    .DW(DW),
    .AW(AW)
) dut (
    .pCLK(CLK),
    .pRESETn(RESETn),
    .pADDR(pADDR),
    .pSEL(pSELx),
    .pENABLE(pENABLE),
    .pWRITE(pWRITE),
    .pWDATA(pWDATA),
    .pRDATA(pRDATA),
    .pREADY(pREADY),
    .pSLVERR(pSLVERR),
    .tx(tx)
);


// Clock generation
initial begin
    CLK = 0;
    forever #5 CLK = ~CLK; // 100MHz clock
end



// VCD dump
initial begin
    $dumpfile("tb_apb_slave.vcd");
    $dumpvars(0, tb_apb_slave);
end

// Test sequence
initial begin
    // Initialize signals
    RESETn = 0;
    pWRITE = 0;
    pSELx = 0;
    pENABLE = 0;
    pWDATA = 0;
    switch = 32'hDEADBEAF;

    RESETn = 0;

    // Reset the DUT
    #10 RESETn = 1;

    // Write to register 0
    apb_write(7'h00, 32'h1);
    apb_write(7'h04, 32'h1);

    for (int i = 0; i < 10; i++) begin
        apb_write(7'h08,32'hA0+i);
    end
    // Test complete

    #1000
    $finish;
end

task apb_write(input [AW-1:0] addr, input [DW-1:0] data);
    begin
        @(posedge CLK);
        pADDR <= addr;
        pWDATA <= data;
        pWRITE <= 1;
        pSELx <= 1;
        pENABLE <= 0;
        @(posedge CLK);
        pENABLE <= 1;
        wait (pREADY);
        @(posedge CLK);
        if (pREADY && pSELx && pENABLE && pWRITE) begin
            $display("Write Successful to address: %h, data: %h", addr, data);
        end else begin
            $display("Write Error at address: %h", addr);
        end
        pSELx <= 0;
        pENABLE <= 0;
    end
endtask


task apb_read(input [AW-1:0] addr);
    begin
        @(posedge CLK);
        pADDR <= addr;
        pWRITE <= 0;
        pSELx <= 1;
        pENABLE <= 0;
        @(posedge CLK);
        pENABLE <= 1;
        wait (pREADY);
        @(posedge CLK);
        if (pREADY && pSELx && pENABLE && !pWRITE) begin
            $display("Read Data from address %h: %h", addr, pRDATA);
        end else begin
            $display("Read Error at address: %h", addr);
        end
        pADDR <= 0;
        pSELx <= 0;
        pENABLE <= 0;
    end
endtask

endmodule